export const projectsList = [
  {
    title: 'Algorithms',
    description: 'Algorithms and Data Structures studies',
    link: 'https://github.com/leandrotk/algorithms',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'FP',
    description: 'A Learning Path for Functional Programming',
    link: 'https://github.com/leandrotk/functional-programming-learning-path',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Programming Language Theory',
    description: 'Studies on Programming Language Theory & Applied PLT',
    link: 'https://github.com/leandrotk/programming-language-theory',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Monkey TS',
    description:
      "The Monkey programming language's compiler written in TypeScript",
    link: 'https://github.com/leandrotk/monkey-ts',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'M2M',
    description: 'Transformation of a Medium post into a Markdown file',
    link: 'https://github.com/LeandroTk/m2m',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Laziness',
    description: 'A set of tools for a better developer experience',
    link: 'https://github.com/leandrotk/laziness',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Thinking in Types',
    description: 'TypeScript examples to build a mental model for types',
    link: 'https://github.com/leandrotk/thinking-in-types',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Advanced TypeScript',
    description: 'Examples of advanced TypeScript patterns',
    link: 'https://github.com/leandrotk/advanced-typescript',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'PomoLambda',
    description: 'A Pomodoro Timer using Functional Programming style',
    link: 'https://github.com/leandrotk/pomo-lambda',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Pokemon',
    description: 'Understanding Higher Order Functions with Pokemon',
    link: 'https://github.com/leandrotk/pokemon',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
];
