export const projectsList = [
  {
    title: 'Algorithms',
    description: 'Algorithms and Data Structures studies',
    link: 'https://github.com/imteekay/algorithms',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Programming Language Theory',
    description: 'Studies on Programming Language Theory & Applied PLT',
    link: 'https://github.com/imteekay/programming-language-theory',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'FP',
    description: 'A Learning Path for Functional Programming',
    link: 'https://github.com/imteekay/functional-programming-learning-path',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Web Performance Research',
    description: 'Research & Experiments in Web Performance',
    link: 'https://github.com/imteekay/web-performance-research',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Frontend Infrastructure',
    description: 'Research & Experiments in Frontend Infrastructure',
    link: 'https://github.com/imteekay/frontend-infrastructure',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Crafting an Interpreter',
    description: 'Crafting an interpreter/compiler with TypeScript',
    link: 'https://github.com/imteekay/crafting-an-interpreter',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Laziness',
    description: 'A set of tools for a better developer experience',
    link: 'https://github.com/imteekay/laziness',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'M2M',
    description: 'Transformation of a Medium post into a Markdown file',
    link: 'https://github.com/imteekay/m2m',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Thinking in Types',
    description: 'TypeScript examples to build a mental model for types',
    link: 'https://github.com/imteekay/thinking-in-types',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Advanced TypeScript',
    description: 'Examples of advanced TypeScript patterns',
    link: 'https://github.com/imteekay/advanced-typescript',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    title: 'Notes',
    description: 'My notes from tech talks',
    link: '/notes',
  },
  {
    title: 'Digital Bookshelf',
    description: "My digital bookshelf — all the books I've read",
    link: '/bookshelf',
  },
  {
    title: 'Microblog',
    description: 'Micro posts about thoughts & reflections',
    link: '/microblog',
  },
];
