export const bookshelfList = [
  {
    link: '/bookshelf/deep-work',
    title: 'Deep Work',
    author: 'Cal Newport',
    reviewLink: 'https://www.goodreads.com/review/show/4032172628',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/10x-is-easier-than-2x',
    title: '10x Is Easier Than 2x',
    author: 'Benjamin Hardy',
    reviewLink: 'https://www.goodreads.com/review/show/5357244882',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: "Man's Search for Meaning",
    author: 'Viktor E. Frankl',
    reviewLink: 'https://www.goodreads.com/review/show/3049811915',
    stars: '⭐️⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'The Almanack of Naval Ravikant',
    author: 'Eric Jorgenson',
    reviewLink: 'https://www.goodreads.com/review/show/5430743328',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'J.K. Rowling',
    reviewLink: 'https://www.goodreads.com/review/show/3059911024',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/14-habits-of-highly-productive-developers',
    title: '14 Habits of Highly Productive Developers',
    author: 'Zeno Rocha',
    reviewLink: 'https://www.goodreads.com/review/show/5404576455',
    stars: '⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Harry Potter and the Philosopher’s Stone',
    author: 'J.K. Rowling',
    reviewLink: 'https://www.goodreads.com/review/show/5394735709',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '/series/building-an-interpreter',
    title: 'Writing An Interpreter In Go',
    author: 'Thorsten Ball',
    reviewLink: 'https://www.goodreads.com/review/show/3726022060',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'High Output Management',
    author: 'Andrew S. Grove',
    reviewLink: 'https://www.goodreads.com/review/show/5324937643',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Build: An Unorthodox Guide to Making Things Worth Making',
    author: 'Tony Fadell',
    reviewLink: 'https://www.goodreads.com/review/show/5088953911',
    stars: '⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/the-intelligence-trap',
    title: 'The Intelligence Trap',
    author: 'David Robson',
    reviewLink: 'https://www.goodreads.com/review/show/5066698681',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/discipline-is-destiny',
    title: 'Discipline is Destiny',
    author: 'Ryan Holliday',
    reviewLink: 'https://www.goodreads.com/review/show/5045949918',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/what-i-talk-about-when-i-talk-about-running',
    title: 'What I Talk about When I Talk about Running',
    author: 'Haruki Murakami',
    reviewLink: 'https://www.goodreads.com/review/show/5045937430',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Range: Why Generalists Triumph in a Specialized World',
    author: 'David Epstein',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Data Structures and Algorithms in Python',
    author: 'Michael T. Goodrich, Roberto Tamassia, Michael H. Goldwasser',
    reviewLink: 'https://www.goodreads.com/review/show/3383863249',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: "Don't Make Me Think",
    author: 'Steve Krug',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'That Will Never Work',
    author: 'Marc Randolph',
    reviewLink: 'https://www.goodreads.com/review/show/4657319942',
    stars: '⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future',
    author: 'Ashlee Vance',
    reviewLink: 'https://www.goodreads.com/review/show/4335923794',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Deep Work',
    author: 'Cal Newport',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Genki I',
    author: 'Eri Banno',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Staff Engineer: Leadership Beyond the Management Track',
    author: 'Will Larson, Tanya Reilly',
    reviewLink: 'https://www.goodreads.com/review/show/3825442347',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    reviewLink: '',
    stars: '⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/atomic-habits',
    title: 'Atomic Habits',
    author: 'James Clear',
    reviewLink: 'https://www.goodreads.com/review/show/2977169188',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Delivering Happiness: A Path to Profits, Passion, and Purpose',
    author: 'Tony Hsieh',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Rework',
    author: 'Jason Fried, David Heinemeier Hansson',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title:
      'The Compound Effect: Jumpstart Your Income, Your Life, Your Success',
    author: 'Darren Hardy',
    reviewLink: 'https://www.goodreads.com/review/show/3050869779',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Leonardo da Vinci',
    author: 'Walter Isaacson',
    reviewLink: 'https://www.goodreads.com/review/show/3049823070',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'The Facebook Effect',
    author: 'David Kirkpatrick',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Outliers: The Story of Success',
    author: 'Malcolm Gladwell',
    reviewLink: '',
    stars: '⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Mastery',
    author: 'Robert Greene',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Peak: Secrets from the New Science of Expertise',
    author: 'K. Anders Ericsson, Robert Pool',
    reviewLink: 'https://www.goodreads.com/review/show/2873292200',
    stars: '⭐️⭐️⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/the-effective-engineer',
    title: 'The Effective Engineer',
    author: 'Edmond Lau',
    reviewLink: 'https://www.goodreads.com/review/show/2744133686',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'The One Thing',
    author: 'Gary Keller, Jay Papasan',
    reviewLink: 'https://www.goodreads.com/review/show/3092808135',
    stars: '⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Dom Casmurro',
    author: 'Machado de Assis',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Originals: How Non-Conformists Move the World',
    author: 'Adam M. Grant',
    reviewLink: 'https://www.goodreads.com/review/show/3108749087',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Refactoring TypeScript',
    author: 'James Hickey',
    reviewLink: '',
    stars: '⭐️⭐️',
  },
];
