export const bookshelfList = [
  {
    link: '/bookshelf/discipline-is-destiny',
    title: 'Discipline is Destiny',
    author: 'Ryan Holliday',
    reviewLink: 'https://www.goodreads.com/review/show/5045949918',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/what-i-talk-about-when-i-talk-about-running',
    title: 'What I Talk about When I Talk about Running',
    author: 'Haruki Murakami',
    reviewLink: 'https://www.goodreads.com/review/show/5045937430',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/the-intelligence-trap',
    title: 'The Intelligence Trap',
    author: 'David Robson',
    reviewLink: 'https://www.goodreads.com/review/show/5066698681',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Build: An Unorthodox Guide to Making Things Worth Making',
    author: 'Tony Fadell',
    reviewLink: 'https://www.goodreads.com/review/show/5088953911',
    stars: '⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'High Output Management',
    author: 'Andrew S. Grove',
    reviewLink: 'https://www.goodreads.com/review/show/5324937643',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future',
    author: 'Ashlee Vance',
    reviewLink: 'https://www.goodreads.com/review/show/4335923794',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Deep Work',
    author: 'Cal Newport',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'That Will Never Work',
    author: 'Marc Randolph',
    reviewLink: 'https://www.goodreads.com/review/show/4657319942',
    stars: '⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/atomic-habits',
    title: 'Atomic Habits',
    author: 'James Clear',
    reviewLink: 'https://www.goodreads.com/review/show/2977169188',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title:
      'The Compound Effect: Jumpstart Your Income, Your Life, Your Success',
    author: 'Darren Hardy',
    reviewLink: 'https://www.goodreads.com/review/show/3050869779',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Leonardo da Vinci',
    author: 'Walter Isaacson',
    reviewLink: 'https://www.goodreads.com/review/show/3049823070',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'The Facebook Effect',
    author: 'David Kirkpatrick',
    reviewLink: 'https://www.goodreads.com/review/show/3027464727',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Outliers: The Story of Success',
    author: 'Malcolm Gladwell',
    reviewLink: 'https://www.goodreads.com/review/show/2971021138',
    stars: '⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Mastery',
    author: 'Robert Greene',
    reviewLink: '',
    stars: '⭐️⭐️⭐️⭐️',
  },
  {
    link: '',
    title: 'Peak: Secrets from the New Science of Expertise',
    author: 'K. Anders Ericsson, Robert Pool',
    reviewLink: 'https://www.goodreads.com/review/show/2873292200',
    stars: '⭐️⭐️⭐️⭐️⭐️',
  },
  {
    link: '/bookshelf/the-effective-engineer',
    title: 'The Effective Engineer',
    author: 'Edmond Lau',
    reviewLink: 'https://www.goodreads.com/review/show/2744133686',
    stars: '⭐️⭐️⭐️⭐️',
  },
];
