export const seriesList = [
  {
    link: '/series/data-structures-in-javascript',
    title: 'Data Structure in JavaScript',
    description: 'Theory and implementation of data structures in JavaScript',
    target: '',
    rel: '',
  },
  {
    link: '/series/crafting-frontend',
    title: 'Crafting Frontend',
    description: 'Research, studies, and practice on the craft of frontend',
    target: '',
    rel: '',
  },
  {
    link: '/series/mastering-javascript',
    title: 'Mastering JavaScript',
    description: 'The process to master JavaScript',
    target: '',
    rel: '',
  },
  {
    link: '/series/frontend-challenges',
    title: 'Frontend Challenges',
    description: 'Design an implementation of frontend challenges',
    target: '',
    rel: '',
  },
  {
    link: '/series/data-structures',
    title: 'Data Structures',
    description: 'Theory and implementation',
    target: '',
    rel: '',
  },
  {
    link: '/series/building-an-interpreter',
    title: 'Building an Interpreter',
    description: 'A compiler from scratch',
    target: '',
    rel: '',
  },
  {
    link: '/series/the-web',
    title: 'The Web',
    description: 'The past, the present, and the future of the web',
    target: '',
    rel: '',
  },
  {
    link: '/series/typescript-learnings',
    title: 'TypeScript Learnings',
    description: 'Everything about TS',
    target: '',
    rel: '',
  },
  {
    link: '/series/algorithms-problem-solving',
    title: 'Algorithms Problem Solving',
    description: 'Documenting algorithms problems I solved',
    target: '',
    rel: '',
  },
  {
    link: '/bookshelf',
    title: 'Digital Bookshelf',
    description: "Documenting the books I've read",
    target: '',
    rel: '',
  },
  {
    link: '/series/rebuilding-mercaris-search',
    title: "Rebuilding Mercari's Search",
    description: 'A Frontend Search Experience Challenge',
    target: '',
    rel: '',
  },
];
